name: Deploy Databricks Config

on:
  push:
    branches:
      - main  # Change to your branch if needed
    paths:
      - 'config/**'  # Triggers only on config changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databrickscfg
          echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databrickscfg

      - name: Upload JSON to Databricks Volume
        run: |
          databricks fs cp config/job_config.json dbfs:/Volumes/vishal-catalog/default/k2_test_volume/job_config.json --overwrite
          # Add lines for more files if needed
